//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ktlyns.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 
	using Kat; 
	using System.Collections.Generic;
	
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class KtlynsParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, WS=3, DEC=4, INT=5, PLUS=6, MINUS=7, SLASH=8, STAR=9, 
		STR=10, LPRN=11, RPRN=12, LBRC=13, RBRC=14, LARR=15, RARR=16, COMMA=17, 
		DOT=18, SDOT=19, EQ=20, IF=21, ELSE=22, AT=23, RET=24, AND=25, OR=26, 
		NOT=27, EQEQ=28, NEQEQ=29, GREAT=30, EQGREAT=31, LESS=32, EQLESS=33, METHOD=34, 
		EXTERNAL=35, ID=36, COMMENT=37, LINE_COMMENT=38;
	public const int
		RULE_program = 0, RULE_block = 1, RULE_statements = 2, RULE_statement = 3, 
		RULE_var_decl = 4, RULE_mth_decl = 5, RULE_ex_mth_decl = 6, RULE_mth = 7, 
		RULE_expr = 8, RULE_unary = 9, RULE_number = 10, RULE_string = 11, RULE_id = 12, 
		RULE_call_args = 13, RULE_mth_decl_arg = 14;
	public static readonly string[] ruleNames = {
		"program", "block", "statements", "statement", "var_decl", "mth_decl", 
		"ex_mth_decl", "mth", "expr", "unary", "number", "string", "id", "call_args", 
		"mth_decl_arg"
	};

	private static readonly string[] _LiteralNames = {
		null, "'['", "']'", null, null, null, "'+'", "'-'", "'/'", "'*'", null, 
		"'('", "')'", "'{'", "'}'", "'<'", "'>'", "','", "'.'", "';'", "'='", 
		"'if'", "'else'", "'@'", "'ret'", "'and'", "'or'", "'not'", "'equals'", 
		"'not equals'", "'great'", "'eq great'", "'less'", "'eq less'", "'method'", 
		"'ext'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "WS", "DEC", "INT", "PLUS", "MINUS", "SLASH", "STAR", 
		"STR", "LPRN", "RPRN", "LBRC", "RBRC", "LARR", "RARR", "COMMA", "DOT", 
		"SDOT", "EQ", "IF", "ELSE", "AT", "RET", "AND", "OR", "NOT", "EQEQ", "NEQEQ", 
		"GREAT", "EQGREAT", "LESS", "EQLESS", "METHOD", "EXTERNAL", "ID", "COMMENT", 
		"LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Ktlyns.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static KtlynsParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public KtlynsParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public KtlynsParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementsContext statements() {
			return GetRuleContext<StatementsContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30;
			statements();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public KBlock Block;
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
	 
		public BlockContext() { }
		public virtual void CopyFrom(BlockContext context) {
			base.CopyFrom(context);
			this.Block = context.Block;
		}
	}
	public partial class RBlockEmptyContext : BlockContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRC() { return GetToken(KtlynsParser.LBRC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRC() { return GetToken(KtlynsParser.RBRC, 0); }
		public RBlockEmptyContext(BlockContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRBlockEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRBlockEmpty(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRBlockEmpty(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RBlockStmtsContext : BlockContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRC() { return GetToken(KtlynsParser.LBRC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementsContext statements() {
			return GetRuleContext<StatementsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRC() { return GetToken(KtlynsParser.RBRC, 0); }
		public RBlockStmtsContext(BlockContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRBlockStmts(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRBlockStmts(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRBlockStmts(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		try {
			State = 38;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				_localctx = new RBlockStmtsContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 32;
				Match(LBRC);
				State = 33;
				statements();
				State = 34;
				Match(RBRC);
				}
				break;
			case 2:
				_localctx = new RBlockEmptyContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 36;
				Match(LBRC);
				State = 37;
				Match(RBRC);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementsContext : ParserRuleContext {
		public KBlock Block;
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public StatementsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statements; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterStatements(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitStatements(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatements(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementsContext statements() {
		StatementsContext _localctx = new StatementsContext(Context, State);
		EnterRule(_localctx, 4, RULE_statements);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 40;
				statement();
				}
				}
				State = 43;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << DEC) | (1L << INT) | (1L << MINUS) | (1L << STR) | (1L << LPRN) | (1L << RET) | (1L << METHOD) | (1L << EXTERNAL) | (1L << ID))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public KStmt Stmt;
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
			this.Stmt = context.Stmt;
		}
	}
	public partial class RStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SDOT() { return GetToken(KtlynsParser.SDOT, 0); }
		public RStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RStatementVarDeclContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl() {
			return GetRuleContext<Var_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SDOT() { return GetToken(KtlynsParser.SDOT, 0); }
		public RStatementVarDeclContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRStatementVarDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRStatementVarDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRStatementVarDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RStatementMthDeclContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Mth_declContext mth_decl() {
			return GetRuleContext<Mth_declContext>(0);
		}
		public RStatementMthDeclContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRStatementMthDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRStatementMthDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRStatementMthDecl(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RStatementExMthDeclContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ex_mth_declContext ex_mth_decl() {
			return GetRuleContext<Ex_mth_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SDOT() { return GetToken(KtlynsParser.SDOT, 0); }
		public RStatementExMthDeclContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRStatementExMthDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRStatementExMthDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRStatementExMthDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement);
		try {
			State = 55;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				_localctx = new RStatementContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 45;
				expr(0);
				State = 46;
				Match(SDOT);
				}
				break;
			case 2:
				_localctx = new RStatementVarDeclContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 48;
				var_decl();
				State = 49;
				Match(SDOT);
				}
				break;
			case 3:
				_localctx = new RStatementMthDeclContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 51;
				mth_decl();
				}
				break;
			case 4:
				_localctx = new RStatementExMthDeclContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 52;
				ex_mth_decl();
				State = 53;
				Match(SDOT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_declContext : ParserRuleContext {
		public KStmt Stmt;
		public Var_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl; } }
	 
		public Var_declContext() { }
		public virtual void CopyFrom(Var_declContext context) {
			base.CopyFrom(context);
			this.Stmt = context.Stmt;
		}
	}
	public partial class RVarDeclExprContext : Var_declContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext[] id() {
			return GetRuleContexts<IdContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id(int i) {
			return GetRuleContext<IdContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(KtlynsParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RVarDeclExprContext(Var_declContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRVarDeclExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRVarDeclExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRVarDeclExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RVarDeclContext : Var_declContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext[] id() {
			return GetRuleContexts<IdContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id(int i) {
			return GetRuleContext<IdContext>(i);
		}
		public RVarDeclContext(Var_declContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRVarDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRVarDecl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRVarDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_declContext var_decl() {
		Var_declContext _localctx = new Var_declContext(Context, State);
		EnterRule(_localctx, 8, RULE_var_decl);
		try {
			State = 65;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				_localctx = new RVarDeclContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 57;
				id(0);
				State = 58;
				id(0);
				}
				break;
			case 2:
				_localctx = new RVarDeclExprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 60;
				id(0);
				State = 61;
				id(0);
				State = 62;
				Match(EQ);
				State = 63;
				expr(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Mth_declContext : ParserRuleContext {
		public KStmt Stmt;
		[System.Diagnostics.DebuggerNonUserCode] public MthContext mth() {
			return GetRuleContext<MthContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPRN() { return GetToken(KtlynsParser.LPRN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Mth_decl_argContext mth_decl_arg() {
			return GetRuleContext<Mth_decl_argContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPRN() { return GetToken(KtlynsParser.RPRN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public Mth_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mth_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterMth_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitMth_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMth_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Mth_declContext mth_decl() {
		Mth_declContext _localctx = new Mth_declContext(Context, State);
		EnterRule(_localctx, 10, RULE_mth_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			mth();
			State = 68;
			id(0);
			State = 69;
			Match(LPRN);
			State = 70;
			mth_decl_arg(0);
			State = 71;
			Match(RPRN);
			State = 72;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ex_mth_declContext : ParserRuleContext {
		public KStmt Stmt;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXTERNAL() { return GetToken(KtlynsParser.EXTERNAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MthContext mth() {
			return GetRuleContext<MthContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPRN() { return GetToken(KtlynsParser.LPRN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Mth_decl_argContext mth_decl_arg() {
			return GetRuleContext<Mth_decl_argContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPRN() { return GetToken(KtlynsParser.RPRN, 0); }
		public Ex_mth_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ex_mth_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterEx_mth_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitEx_mth_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEx_mth_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ex_mth_declContext ex_mth_decl() {
		Ex_mth_declContext _localctx = new Ex_mth_declContext(Context, State);
		EnterRule(_localctx, 12, RULE_ex_mth_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			Match(EXTERNAL);
			State = 75;
			mth();
			State = 76;
			id(0);
			State = 77;
			Match(LPRN);
			State = 78;
			mth_decl_arg(0);
			State = 79;
			Match(RPRN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MthContext : ParserRuleContext {
		public KId Id;
		public MthContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mth; } }
	 
		public MthContext() { }
		public virtual void CopyFrom(MthContext context) {
			base.CopyFrom(context);
			this.Id = context.Id;
		}
	}
	public partial class RMthVoidContext : MthContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode METHOD() { return GetToken(KtlynsParser.METHOD, 0); }
		public RMthVoidContext(MthContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRMthVoid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRMthVoid(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRMthVoid(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RMthTypeContext : MthContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode METHOD() { return GetToken(KtlynsParser.METHOD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LARR() { return GetToken(KtlynsParser.LARR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RARR() { return GetToken(KtlynsParser.RARR, 0); }
		public RMthTypeContext(MthContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRMthType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRMthType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRMthType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MthContext mth() {
		MthContext _localctx = new MthContext(Context, State);
		EnterRule(_localctx, 14, RULE_mth);
		try {
			State = 87;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				_localctx = new RMthVoidContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 81;
				Match(METHOD);
				}
				break;
			case 2:
				_localctx = new RMthTypeContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 82;
				Match(METHOD);
				State = 83;
				Match(LARR);
				State = 84;
				id(0);
				State = 85;
				Match(RARR);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public KExpr Expr;
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
			this.Expr = context.Expr;
		}
	}
	public partial class RExprUnaryContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public UnaryContext unary() {
			return GetRuleContext<UnaryContext>(0);
		}
		public RExprUnaryContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprUnary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprUnary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprUnary(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprBinDivContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(KtlynsParser.SLASH, 0); }
		public RExprBinDivContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprBinDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprBinDiv(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprBinDiv(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprBinAddContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(KtlynsParser.PLUS, 0); }
		public RExprBinAddContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprBinAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprBinAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprBinAdd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprBinSubContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(KtlynsParser.MINUS, 0); }
		public RExprBinSubContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprBinSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprBinSub(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprBinSub(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprAssignContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(KtlynsParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RExprAssignContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprAssign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprAssign(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprAssign(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprCallContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPRN() { return GetToken(KtlynsParser.LPRN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Call_argsContext call_args() {
			return GetRuleContext<Call_argsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPRN() { return GetToken(KtlynsParser.RPRN, 0); }
		public RExprCallContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprBinMultContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STAR() { return GetToken(KtlynsParser.STAR, 0); }
		public RExprBinMultContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprBinMult(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprBinMult(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprBinMult(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprReturnContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RET() { return GetToken(KtlynsParser.RET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RExprReturnContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprReturn(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprReturn(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprReturn(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprStringContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public RExprStringContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprGroupContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPRN() { return GetToken(KtlynsParser.LPRN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPRN() { return GetToken(KtlynsParser.RPRN, 0); }
		public RExprGroupContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprGroup(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprGroup(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprGroup(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RExprIdContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public RExprIdContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRExprId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRExprId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRExprId(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 16;
		EnterRecursionRule(_localctx, 16, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 110;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				_localctx = new RExprStringContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 90;
				@string();
				}
				break;
			case 2:
				{
				_localctx = new RExprIdContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 91;
				id(0);
				}
				break;
			case 3:
				{
				_localctx = new RExprAssignContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 92;
				id(0);
				State = 93;
				Match(EQ);
				State = 94;
				expr(9);
				}
				break;
			case 4:
				{
				_localctx = new RExprCallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 96;
				id(0);
				State = 97;
				Match(LPRN);
				State = 98;
				call_args(0);
				State = 99;
				Match(RPRN);
				}
				break;
			case 5:
				{
				_localctx = new RExprGroupContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 101;
				Match(LPRN);
				State = 102;
				expr(0);
				State = 103;
				Match(RPRN);
				}
				break;
			case 6:
				{
				_localctx = new RExprUnaryContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 105;
				unary();
				}
				break;
			case 7:
				{
				_localctx = new RExprReturnContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 106;
				Match(RET);
				State = 108;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
				case 1:
					{
					State = 107;
					expr(0);
					}
					break;
				}
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 126;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 124;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
					case 1:
						{
						_localctx = new RExprBinMultContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 112;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 113;
						Match(STAR);
						State = 114;
						expr(6);
						}
						break;
					case 2:
						{
						_localctx = new RExprBinDivContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 115;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 116;
						Match(SLASH);
						State = 117;
						expr(5);
						}
						break;
					case 3:
						{
						_localctx = new RExprBinAddContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 118;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 119;
						Match(PLUS);
						State = 120;
						expr(4);
						}
						break;
					case 4:
						{
						_localctx = new RExprBinSubContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 121;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 122;
						Match(MINUS);
						State = 123;
						expr(3);
						}
						break;
					}
					} 
				}
				State = 128;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class UnaryContext : ParserRuleContext {
		public KExpr Expr;
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(KtlynsParser.MINUS, 0); }
		public UnaryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unary; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterUnary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitUnary(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnary(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryContext unary() {
		UnaryContext _localctx = new UnaryContext(Context, State);
		EnterRule(_localctx, 18, RULE_unary);
		try {
			State = 132;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DEC:
			case INT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 129;
				number();
				}
				break;
			case MINUS:
				EnterOuterAlt(_localctx, 2);
				{
				State = 130;
				Match(MINUS);
				State = 131;
				number();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public KExpr Expr;
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
	 
		public NumberContext() { }
		public virtual void CopyFrom(NumberContext context) {
			base.CopyFrom(context);
			this.Expr = context.Expr;
		}
	}
	public partial class RNumberDecContext : NumberContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEC() { return GetToken(KtlynsParser.DEC, 0); }
		public RNumberDecContext(NumberContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRNumberDec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRNumberDec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRNumberDec(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RNumberIntContext : NumberContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(KtlynsParser.INT, 0); }
		public RNumberIntContext(NumberContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRNumberInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRNumberInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRNumberInt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 20, RULE_number);
		try {
			State = 136;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
				_localctx = new RNumberIntContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 134;
				Match(INT);
				}
				break;
			case DEC:
				_localctx = new RNumberDecContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 135;
				Match(DEC);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		public KStr Str;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STR() { return GetToken(KtlynsParser.STR, 0); }
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 22, RULE_string);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			Match(STR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdContext : ParserRuleContext {
		public KId Id;
		public IdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id; } }
	 
		public IdContext() { }
		public virtual void CopyFrom(IdContext context) {
			base.CopyFrom(context);
			this.Id = context.Id;
		}
	}
	public partial class RIDPointerContext : IdContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STAR() { return GetToken(KtlynsParser.STAR, 0); }
		public RIDPointerContext(IdContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRIDPointer(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRIDPointer(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRIDPointer(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RIDArrayContext : IdContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(KtlynsParser.INT, 0); }
		public RIDArrayContext(IdContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRIDArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRIDArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRIDArray(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RIDSimpleContext : IdContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(KtlynsParser.ID, 0); }
		public RIDSimpleContext(IdContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRIDSimple(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRIDSimple(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRIDSimple(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdContext id() {
		return id(0);
	}

	private IdContext id(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		IdContext _localctx = new IdContext(Context, _parentState);
		IdContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_id, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new RIDSimpleContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 141;
			Match(ID);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 153;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 151;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
					case 1:
						{
						_localctx = new RIDArrayContext(new IdContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_id);
						State = 143;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 144;
						Match(T__0);
						State = 146;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if (_la==INT) {
							{
							State = 145;
							Match(INT);
							}
						}

						State = 148;
						Match(T__1);
						}
						break;
					case 2:
						{
						_localctx = new RIDPointerContext(new IdContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_id);
						State = 149;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 150;
						Match(STAR);
						}
						break;
					}
					} 
				}
				State = 155;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Call_argsContext : ParserRuleContext {
		public List<KExpr> Exprs;
		public Call_argsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call_args; } }
	 
		public Call_argsContext() { }
		public virtual void CopyFrom(Call_argsContext context) {
			base.CopyFrom(context);
			this.Exprs = context.Exprs;
		}
	}
	public partial class RCallArgsAddContext : Call_argsContext {
		[System.Diagnostics.DebuggerNonUserCode] public Call_argsContext call_args() {
			return GetRuleContext<Call_argsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(KtlynsParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RCallArgsAddContext(Call_argsContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRCallArgsAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRCallArgsAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRCallArgsAdd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RCallArgsExprContext : Call_argsContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public RCallArgsExprContext(Call_argsContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRCallArgsExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRCallArgsExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRCallArgsExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RCallArgsContext : Call_argsContext {
		public RCallArgsContext(Call_argsContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRCallArgs(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRCallArgs(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRCallArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Call_argsContext call_args() {
		return call_args(0);
	}

	private Call_argsContext call_args(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Call_argsContext _localctx = new Call_argsContext(Context, _parentState);
		Call_argsContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_call_args, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 158;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				_localctx = new RCallArgsContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				}
				break;
			case 2:
				{
				_localctx = new RCallArgsExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 157;
				expr(0);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 165;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new RCallArgsAddContext(new Call_argsContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_call_args);
					State = 160;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 161;
					Match(COMMA);
					State = 162;
					expr(0);
					}
					} 
				}
				State = 167;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Mth_decl_argContext : ParserRuleContext {
		public List<KVarDecl> Decls;
		public Mth_decl_argContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mth_decl_arg; } }
	 
		public Mth_decl_argContext() { }
		public virtual void CopyFrom(Mth_decl_argContext context) {
			base.CopyFrom(context);
			this.Decls = context.Decls;
		}
	}
	public partial class RMthDeclArgContext : Mth_decl_argContext {
		public RMthDeclArgContext(Mth_decl_argContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRMthDeclArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRMthDeclArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRMthDeclArg(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RMthDeclArgAddContext : Mth_decl_argContext {
		[System.Diagnostics.DebuggerNonUserCode] public Mth_decl_argContext mth_decl_arg() {
			return GetRuleContext<Mth_decl_argContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(KtlynsParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl() {
			return GetRuleContext<Var_declContext>(0);
		}
		public RMthDeclArgAddContext(Mth_decl_argContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRMthDeclArgAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRMthDeclArgAdd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRMthDeclArgAdd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RMthDeclArgVarContext : Mth_decl_argContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_declContext var_decl() {
			return GetRuleContext<Var_declContext>(0);
		}
		public RMthDeclArgVarContext(Mth_decl_argContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.EnterRMthDeclArgVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IKtlynsListener typedListener = listener as IKtlynsListener;
			if (typedListener != null) typedListener.ExitRMthDeclArgVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKtlynsVisitor<TResult> typedVisitor = visitor as IKtlynsVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRMthDeclArgVar(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Mth_decl_argContext mth_decl_arg() {
		return mth_decl_arg(0);
	}

	private Mth_decl_argContext mth_decl_arg(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Mth_decl_argContext _localctx = new Mth_decl_argContext(Context, _parentState);
		Mth_decl_argContext _prevctx = _localctx;
		int _startState = 28;
		EnterRecursionRule(_localctx, 28, RULE_mth_decl_arg, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 170;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				{
				_localctx = new RMthDeclArgContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				}
				break;
			case 2:
				{
				_localctx = new RMthDeclArgVarContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 169;
				var_decl();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 177;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new RMthDeclArgAddContext(new Mth_decl_argContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_mth_decl_arg);
					State = 172;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 173;
					Match(COMMA);
					State = 174;
					var_decl();
					}
					} 
				}
				State = 179;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 8: return expr_sempred((ExprContext)_localctx, predIndex);
		case 12: return id_sempred((IdContext)_localctx, predIndex);
		case 13: return call_args_sempred((Call_argsContext)_localctx, predIndex);
		case 14: return mth_decl_arg_sempred((Mth_decl_argContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		case 1: return Precpred(Context, 4);
		case 2: return Precpred(Context, 3);
		case 3: return Precpred(Context, 2);
		}
		return true;
	}
	private bool id_sempred(IdContext _localctx, int predIndex) {
		switch (predIndex) {
		case 4: return Precpred(Context, 2);
		case 5: return Precpred(Context, 1);
		}
		return true;
	}
	private bool call_args_sempred(Call_argsContext _localctx, int predIndex) {
		switch (predIndex) {
		case 6: return Precpred(Context, 1);
		}
		return true;
	}
	private bool mth_decl_arg_sempred(Mth_decl_argContext _localctx, int predIndex) {
		switch (predIndex) {
		case 7: return Precpred(Context, 1);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '(', '\xB7', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', ')', '\n', '\x3', '\x3', 
		'\x4', '\x6', '\x4', ',', '\n', '\x4', '\r', '\x4', '\xE', '\x4', '-', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x5', '\x5', ':', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', '\x44', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x5', '\t', 'Z', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', 
		'\n', 'o', '\n', '\n', '\x5', '\n', 'q', '\n', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\a', 
		'\n', '\x7F', '\n', '\n', '\f', '\n', '\xE', '\n', '\x82', '\v', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\x87', '\n', '\v', 
		'\x3', '\f', '\x3', '\f', '\x5', '\f', '\x8B', '\n', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x5', '\xE', '\x95', '\n', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x9A', '\n', '\xE', '\f', '\xE', 
		'\xE', '\xE', '\x9D', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', '\xA1', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\a', '\xF', '\xA6', '\n', '\xF', '\f', '\xF', '\xE', '\xF', '\xA9', '\v', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xAD', '\n', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\xB2', '\n', 
		'\x10', '\f', '\x10', '\xE', '\x10', '\xB5', '\v', '\x10', '\x3', '\x10', 
		'\x2', '\x6', '\x12', '\x1A', '\x1C', '\x1E', '\x11', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x1E', '\x2', '\x2', '\x2', '\xC2', '\x2', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x4', '(', '\x3', '\x2', '\x2', '\x2', '\x6', '+', '\x3', 
		'\x2', '\x2', '\x2', '\b', '\x39', '\x3', '\x2', '\x2', '\x2', '\n', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\f', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\xE', 'L', '\x3', '\x2', '\x2', '\x2', '\x10', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '\x12', 'p', '\x3', '\x2', '\x2', '\x2', '\x14', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x18', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', ' ', '!', '\x5', '\x6', '\x4', '\x2', '!', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\"', '#', '\a', '\xF', '\x2', '\x2', '#', 
		'$', '\x5', '\x6', '\x4', '\x2', '$', '%', '\a', '\x10', '\x2', '\x2', 
		'%', ')', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\a', '\xF', '\x2', '\x2', 
		'\'', ')', '\a', '\x10', '\x2', '\x2', '(', '\"', '\x3', '\x2', '\x2', 
		'\x2', '(', '&', '\x3', '\x2', '\x2', '\x2', ')', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '*', ',', '\x5', '\b', '\x5', '\x2', '+', '*', '\x3', '\x2', 
		'\x2', '\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', '-', '+', '\x3', '\x2', 
		'\x2', '\x2', '-', '.', '\x3', '\x2', '\x2', '\x2', '.', '\a', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\x5', '\x12', '\n', '\x2', '\x30', 
		'\x31', '\a', '\x15', '\x2', '\x2', '\x31', ':', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x33', '\x5', '\n', '\x6', '\x2', '\x33', '\x34', '\a', 
		'\x15', '\x2', '\x2', '\x34', ':', '\x3', '\x2', '\x2', '\x2', '\x35', 
		':', '\x5', '\f', '\a', '\x2', '\x36', '\x37', '\x5', '\xE', '\b', '\x2', 
		'\x37', '\x38', '\a', '\x15', '\x2', '\x2', '\x38', ':', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '/', '\x3', '\x2', '\x2', '\x2', '\x39', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x39', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\x39', '\x36', '\x3', '\x2', '\x2', '\x2', ':', '\t', '\x3', '\x2', '\x2', 
		'\x2', ';', '<', '\x5', '\x1A', '\xE', '\x2', '<', '=', '\x5', '\x1A', 
		'\xE', '\x2', '=', '\x44', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x5', 
		'\x1A', '\xE', '\x2', '?', '@', '\x5', '\x1A', '\xE', '\x2', '@', '\x41', 
		'\a', '\x16', '\x2', '\x2', '\x41', '\x42', '\x5', '\x12', '\n', '\x2', 
		'\x42', '\x44', '\x3', '\x2', '\x2', '\x2', '\x43', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x43', '>', '\x3', '\x2', '\x2', '\x2', '\x44', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\x46', '\x5', '\x10', '\t', '\x2', '\x46', 
		'G', '\x5', '\x1A', '\xE', '\x2', 'G', 'H', '\a', '\r', '\x2', '\x2', 
		'H', 'I', '\x5', '\x1E', '\x10', '\x2', 'I', 'J', '\a', '\xE', '\x2', 
		'\x2', 'J', 'K', '\x5', '\x4', '\x3', '\x2', 'K', '\r', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'M', '\a', '%', '\x2', '\x2', 'M', 'N', '\x5', '\x10', 
		'\t', '\x2', 'N', 'O', '\x5', '\x1A', '\xE', '\x2', 'O', 'P', '\a', '\r', 
		'\x2', '\x2', 'P', 'Q', '\x5', '\x1E', '\x10', '\x2', 'Q', 'R', '\a', 
		'\xE', '\x2', '\x2', 'R', '\xF', '\x3', '\x2', '\x2', '\x2', 'S', 'Z', 
		'\a', '$', '\x2', '\x2', 'T', 'U', '\a', '$', '\x2', '\x2', 'U', 'V', 
		'\a', '\x11', '\x2', '\x2', 'V', 'W', '\x5', '\x1A', '\xE', '\x2', 'W', 
		'X', '\a', '\x12', '\x2', '\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'S', '\x3', '\x2', '\x2', '\x2', 'Y', 'T', '\x3', '\x2', '\x2', '\x2', 
		'Z', '\x11', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\b', '\n', '\x1', 
		'\x2', '\\', 'q', '\x5', '\x18', '\r', '\x2', ']', 'q', '\x5', '\x1A', 
		'\xE', '\x2', '^', '_', '\x5', '\x1A', '\xE', '\x2', '_', '`', '\a', '\x16', 
		'\x2', '\x2', '`', '\x61', '\x5', '\x12', '\n', '\v', '\x61', 'q', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x63', '\x5', '\x1A', '\xE', '\x2', '\x63', 
		'\x64', '\a', '\r', '\x2', '\x2', '\x64', '\x65', '\x5', '\x1C', '\xF', 
		'\x2', '\x65', '\x66', '\a', '\xE', '\x2', '\x2', '\x66', 'q', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\a', '\r', '\x2', '\x2', 'h', 'i', '\x5', 
		'\x12', '\n', '\x2', 'i', 'j', '\a', '\xE', '\x2', '\x2', 'j', 'q', '\x3', 
		'\x2', '\x2', '\x2', 'k', 'q', '\x5', '\x14', '\v', '\x2', 'l', 'n', '\a', 
		'\x1A', '\x2', '\x2', 'm', 'o', '\x5', '\x12', '\n', '\x2', 'n', 'm', 
		'\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 
		'q', '\x3', '\x2', '\x2', '\x2', 'p', '[', '\x3', '\x2', '\x2', '\x2', 
		'p', ']', '\x3', '\x2', '\x2', '\x2', 'p', '^', '\x3', '\x2', '\x2', '\x2', 
		'p', '\x62', '\x3', '\x2', '\x2', '\x2', 'p', 'g', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'k', '\x3', '\x2', '\x2', '\x2', 'p', 'l', '\x3', '\x2', '\x2', 
		'\x2', 'q', '\x80', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\f', '\a', 
		'\x2', '\x2', 's', 't', '\a', '\v', '\x2', '\x2', 't', '\x7F', '\x5', 
		'\x12', '\n', '\b', 'u', 'v', '\f', '\x6', '\x2', '\x2', 'v', 'w', '\a', 
		'\n', '\x2', '\x2', 'w', '\x7F', '\x5', '\x12', '\n', '\a', 'x', 'y', 
		'\f', '\x5', '\x2', '\x2', 'y', 'z', '\a', '\b', '\x2', '\x2', 'z', '\x7F', 
		'\x5', '\x12', '\n', '\x6', '{', '|', '\f', '\x4', '\x2', '\x2', '|', 
		'}', '\a', '\t', '\x2', '\x2', '}', '\x7F', '\x5', '\x12', '\n', '\x5', 
		'~', 'r', '\x3', '\x2', '\x2', '\x2', '~', 'u', '\x3', '\x2', '\x2', '\x2', 
		'~', 'x', '\x3', '\x2', '\x2', '\x2', '~', '{', '\x3', '\x2', '\x2', '\x2', 
		'\x7F', '\x82', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x83', '\x87', '\x5', '\x16', '\f', '\x2', '\x84', '\x85', '\a', '\t', 
		'\x2', '\x2', '\x85', '\x87', '\x5', '\x16', '\f', '\x2', '\x86', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x15', '\x3', '\x2', '\x2', '\x2', '\x88', '\x8B', '\a', '\a', 
		'\x2', '\x2', '\x89', '\x8B', '\a', '\x6', '\x2', '\x2', '\x8A', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\x17', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', '\f', 
		'\x2', '\x2', '\x8D', '\x19', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', 
		'\b', '\xE', '\x1', '\x2', '\x8F', '\x90', '\a', '&', '\x2', '\x2', '\x90', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\f', '\x4', '\x2', 
		'\x2', '\x92', '\x94', '\a', '\x3', '\x2', '\x2', '\x93', '\x95', '\a', 
		'\a', '\x2', '\x2', '\x94', '\x93', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x9A', '\a', '\x4', '\x2', '\x2', '\x97', '\x98', '\f', 
		'\x3', '\x2', '\x2', '\x98', '\x9A', '\a', '\v', '\x2', '\x2', '\x99', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\xA1', '\b', '\xF', '\x1', '\x2', '\x9F', '\xA1', '\x5', 
		'\x12', '\n', '\x2', '\xA0', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\xA3', '\f', '\x3', '\x2', '\x2', '\xA3', '\xA4', '\a', 
		'\x13', '\x2', '\x2', '\xA4', '\xA6', '\x5', '\x12', '\n', '\x2', '\xA5', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xA9', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAD', '\b', '\x10', '\x1', 
		'\x2', '\xAB', '\xAD', '\x5', '\n', '\x6', '\x2', '\xAC', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\f', '\x3', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', '\x13', '\x2', '\x2', '\xB0', '\xB2', '\x5', 
		'\n', '\x6', '\x2', '\xB1', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'(', '-', '\x39', '\x43', 'Y', 'n', 'p', '~', '\x80', '\x86', '\x8A', 
		'\x94', '\x99', '\x9B', '\xA0', '\xA7', '\xAC', '\xB3',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
